apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::976396441368:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-T2NKX997MXDG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::976396441368:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-29T13:00:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1505"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8cff7f6f-6c41-440a-a47e-9ddb87c28605
